---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# agRee

<!-- badges: start -->
<!-- badges: end -->

The goal of agRee is to provide a set of simple tools to assess agreement 
between two datasets. 

## Installation

<!-- You can install the released version of agRee from [CRAN](https://CRAN.R-project.org) with: -->
There is no released version of agRee yet. 

<!-- ``` r -->
<!-- install.packages("agRee") -->
<!-- ``` -->

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("lucas-johnson/agRee")
```

## Example

This is a basic example which shows you how to compute AC (agreement 
coefficient), ACs (systematic agreement) and ACu (unsystematic agreement):

```{r example}
library(agRee)
# TODO: fill in example code here. 
```
